version: 2.1

executors:
  blaser-executor:
    docker:
      - image: themattrix/tox
    environment:
      LOCALE: en_US.utf8

commands:
  prep-environment:
    steps:
      - checkout
      - run: pip install tox
  run-tests:
    steps:
      - run: tox
  codecov:
    steps:
      - run: bash <(curl -s https://codecov.io/bash)
  commit-changes:
    steps:
      - deploy:
          name: "Trigger content deployment"
          command: |
            git config credential.helper "cache --timeout=120"
            git config user.email "ericroc.how@gmail.com"
            git config user.name "DeployTron 9000"
            git add docs/*
            git commit -am "circleci content push [skip ci]"
            git push -q https://${BLASERBOT_GITHUB_TOKEN}@github.com/ericrochow/blaser.git dev

jobs:
  build:
    executor: blaser-executor
    working_directory: "~/blaser"
    steps:
      - prep-environment
      - run-tests
      - codecov

workflows:
  commit:
    jobs:
      - build
